### ISSUE TITLE
Clearer Documentation regarding Usage

### ISSUE THREAD

**Issue by micnguyen** [Fausto95/rn-async-storage-flipper#11]
Hi,

Thanks for the library. I am a big fan of it. I am a little confused about how to use it though.

The README mentions that we should use `RNAsyncStorageFlipper(AsyncStorage)` - but do we do this just once, or do we run this every time we want to update the reading from the Database? Because I do it once in `App.js` and the values never update.

Thanks.

**Comment by Fausto95** [comment]
We should only do it once, and as mentioned in #12, a `Refresh` button would fix this issue.

**Comment by micnguyen** [comment]
I see. That makes sense. I'll see if I can find some free time to add the PR as well. Thanks for the plugin.
