### ISSUE TITLE
 @react-native-community/async-storage peerDependency

### ISSUE THREAD

**Issue by joeyfigaro** [Fausto95/rn-async-storage-flipper#22]
`rn-async-storage-flipper` depends on `@react-native-community/async-storage`, but they've split off into their own org: ` @react-native-async-storage/async-storage`

**Comment by Fausto95** [comment]
Do you mind sending a pull request to fix this?

**Comment by joeyfigaro** [comment]
@Fausto95 hot damn, your response was so fast I did a double-take! 🔥 I'd be happy to. Will have up within next day or two. 💪🏻

**Comment by joeyfigaro** [comment]
Base PR is done–will take a stab at testing impact of changes. Let me know if anything else needs to change or occur to get this guy merged, and thanks!

**Comment by Fausto95** [comment]
Looks fine! Will merge it now and release it by tomorrow

**Comment by joeyfigaro** [comment]
Thanks @Fausto95 🔥
