### ISSUE TITLE
react-native-flipper hard dependency

### ISSUE THREAD

**Issue by joeyfigaro** [Fausto95/rn-async-storage-flipper#24]
It looks like the plugin has both a dependency and peerDependency on `react-native-flipper` `v0.37.0`, which is causing peer requirements to fail (for version 0.83.0) in yarn. 

https://github.com/Fausto95/rn-async-storage-flipper/blob/48a063e85b39594fa99e385265c62a013f53c599/packages/rn-async-storage-flipper/package.json#L25-L27

If you need this provided for developing locally, is it safe to remove `dependencies` entirely and rely on `devDependencies`?

**Comment by Fausto95** [comment]
Merged! Thanks.
